### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by cmckni3** [pugjs/pug-loader#33]
```
[REDACTED]/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:81
    r.forEach(function(r) {
      ^
TypeError: undefined is not a function
  at [REDACTED]/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:81:5
  at Array.reduce (native)
  at LoadersList.match ([REDACTED]/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:80:27)
  at [REDACTED]/node_modules/webpack/lib/NormalModuleFactory.js:111:68
  at [REDACTED]/node_modules/webpack/node_modules/async/lib/async.js:726:13
  at [REDACTED]/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done ([REDACTED]/node_modules/webpack/node_modules/async/lib/async.js:246:17)
  at [REDACTED]/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at [REDACTED]/node_modules/webpack/node_modules/async/lib/async.js:723:17
  at [REDACTED]/node_modules/webpack/node_modules/async/lib/async.js:167:37
  at [REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:28:24
  at onResolved ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:39:10)
  at [REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:123:21
  at [REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
  at applyPluginsParallelBailResult.createInnerCallback.log ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:104:30)
  at loggingCallbackWrapper ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
  at [REDACTED]/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
  at innerCallback ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:90:37)
  at loggingCallbackWrapper ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
  at [REDACTED]/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
  at Tapable.<anonymous> ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFileFieldAliasPlugin.js:101:26)
  at [REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFileFieldAliasPlugin.js:52:26
  at Storage.provide ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
  at CachedInputFileSystem.readFile ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
  at findDescriptionFile ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFileFieldAliasPlugin.js:16:23)
  at [REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFileFieldAliasPlugin.js:22:13
  at Storage.provide ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
  at CachedInputFileSystem.readFile ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
  at findDescriptionFile ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFileFieldAliasPlugin.js:16:23)
  at [REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFileFieldAliasPlugin.js:22:13
  at Storage.finished ([REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
  at [REDACTED]/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:76:16
  at fs.js:263:20
  at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by cmckni3** [comment]
webpack.config.js

```
...
{ test: /\.jade$/, loaders: 'jade' }
...
```

`jade-loader` is in my package.json under `devDependencies`

**Comment by cmckni3** [comment]
Nevermind, I messed up my loader in my webpack.config.js. I put "loaders" instead of "loader"
