### ISSUE TITLE
if conditions seems not work

### ISSUE THREAD

**Issue by vladyslav2** [pugjs/pug-loader#55]
content in pug file:

```
      if user.token
          p hello

```

running pug like this:

```
let template = require('pug!templates/menuNotification.pug');   
```

getting error:

```
Module build failed: Error: /Users/admin/projects/gfwhitelabels/webpack/node_modules/pug-loader/index.js!/Users/admin/projects/gfwhitelabels/webpack/src/templates/menuNotification.pug:5:1
    3| function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;;var locals_for_with = (locals || {});(function (user) {if (user.token) {
    4| pug_html = pug_html + "\u003Cli class=\"nav-item notification notification-bell text-center\"\u003E\u003Ca href=\"#\"\u003E\u003Ci class=\"fa fa-bell-o\"\u003E\u003Cspan class=\"count-notific\"\u003E5\u003C\u002Fspan\u003E\u003C\u002Fi\u003E\u003C\u002Fa\u003E\u003Cdiv class=\"list-container notification-container\"\u003E\u003Cul class=\"submenu list-unstyled\"\u003E \u003Cli class=\"clearfix title nav-link\"\u003E\u003Cspan class=\"pull-left\"\u003E\u003Cb\u003E5 pending \u003C\u002Fb\u003E comments\u003C\u002Fspan\u003E\u003Ca class=\"pull-right\" href=\"#\"\u003E view all\u003C\u002Fa\u003E\u003C\u002Fli\u003E\u003Cli class=\"clearfix nav-link\"\u003E\u003Cspan class=\"pull-left\"\u003EMaria Kravchuk wrote...\u003C\u002Fspan\u003E\u003Ci class=\"pull-right\"\u003Ejust now\u003C\u002Fi\u003E\u003C\u002Fli\u003E\u003Cli class=\"clearfix nav-link\"\u003E\u003Cspan class=\"pull-left\"\u003EMaria Kravchuk wrote...\u003C\u002Fspan\u003E\u003Ci class=\"pull-right\"\u003Ejust now\u003C\u002Fi\u003E\u003C\u002Fli\u003E\u003Cli class=\"clearfix nav-link\"\u003E\u003Cspan class=\"pull-left\"\u003EMaria Kravchuk wrote...\u003C\u002Fspan\u003E\u003Ci class=\"pull-right\"\u003Ejust now\u003C\u002Fi\u003E\u003C\u002Fli\u003E\u003Cli class=\"clearfix nav-link\"\u003E\u003Cspan class=\"pull-left\"\u003EMaria Kravchuk wrote...\u003C\u002Fspan\u003E\u003Ci class=\"pull-right\"\u003Ejust now\u003C\u002Fi\u003E\u003C\u002Fli\u003E\u003C\u002Ful\u003E\u003C\u002Fdiv\u003E\u003C\u002Fli\u003E";
  > 5| }}.call(this,"user" in locals_for_with?locals_for_with.user:typeof user!=="undefined"?user:undefined));;return pug_html;};

     6| module.exports = template;

unexpected text "}}.ca"
    at makeError (/Users/admin/projects/gfwhitelabels/webpack/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/Users/admin/projects/gfwhitelabels/webpack/node_modules/pug-lexer/index.js:58:15)
```

looks like pug generate template functions with .call and there is no way to

**Comment by vladyslav2** [comment]
Figure that out.

Problem was that i added extension to webpack  and load template with
`require('pug!templates/menuNotification.pug');`

instead of
`require('templates/menuNotification.pug');`

**Comment by TimothyGu** [comment]
If you already bound `.pug` extension to the pug-loader, I think Webpack might interpret your original code as being `pug!pug!file.pug`. Either way, glad to hear the issue has been resolved :)
